
export interface Solicitud {
    solicitud_id?,
    fecha_solicitud?,
    beneficiario_id?,
    motivo?,
    email?,
    telefono1?,
    telefono2?,
    tipo_solicitud_id?,
    tipo_cobertura_id?,
    especialidad_id?,
    medico_id?,
    origen_id?,
    estado_solicitud_id?,
    causa_solicitud_id?,
    observacion?,
    usuario_creador?,
    nombre_creador?,
    usuario_modificador?,
    nombre_modificador?,
    created?,
    modified?,

    parentesco?,
    nombre_titular?,
    apellido_titular?,
    nombre_beneficiario?,
    apellido_beneficiario?,
    cedula_titular?,
    cedula_beneficiario?,

    nombre_tipo_solicitud?,
    nombre_tipo_cobertura_id?,
    nombre_estado_solicitud?,
    nombre_especialidad?,
    cedula_hcm?,
    fecha_recepcion?,

    tipo_atencion_id?,
    nombre_tipo_atencion?,
    diagnostico_id?,
    domicilio_id?,
    prioridad_id?,

}